src/Entity/SavedFilters.php
<?php

declare(strict_types=1);

namespace Presta\SonataSavedFiltersBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Presta\SonataSavedFiltersBundle\Repository\SavedFiltersRepository;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: SavedFiltersRepository::class)]
#[ORM\Table(name: 'presta_sonata_saved_filters')]
class SavedFilters
{
    #[ORM\Column(type: 'integer')]
    #[ORM\Id]
    #[ORM\GeneratedValue]
    private ?int $id = null;

    #[ORM\Column(type: 'string')]
    #[Assert\NotBlank]
    #[Assert\NotNull]
    private ?string $name = null;

    #[ORM\Column(type: 'string')]
    #[Assert\NotBlank]
    #[Assert\NotNull]
    private ?string $adminClass = null;

    /**
     * @var array<string, mixed>|null
     */
    #[ORM\Column(type: 'json')]
    #[Assert\NotNull]
    private ?array $filters = null;

    #[ORM\Column(type: 'boolean', name: '`public`')]
    private bool $public = false;

    #[ORM\Column(type: 'boolean', name: '`protected`')]
    private bool $protected = false;

    /**
     * @var Collection<int, SavedFiltersOwnerInterface>
     */
    #[ORM\ManyToMany(targetEntity: SavedFiltersOwnerInterface::class)]
    #[ORM\JoinTable(name: 'presta_sonata_saved_filters_owners')]
    #[ORM\JoinColumn(name: 'filters_id')]
    #[ORM\InverseJoinColumn(name: 'owner_id')]
    private Collection $ownersWithAccess;

    public function __construct()
    {
        $this->ownersWithAccess = new ArrayCollection();
    }

    public function getFiltersQueryString(): string
    {
        if (!is_array($this->filters) || 0 === count($this->filters)) {
            return '';
        }

        return '?' . http_build_query($this->filters);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    public function getAdminClass(): ?string
    {
        return $this->adminClass;
    }

    public function setAdminClass(?string $adminClass): void
    {
        $this->adminClass = $adminClass;
    }

    /**
     * @return array<string, mixed>|null
     */
    public function getFilters(): ?array
    {
        return $this->filters;
    }

    public function setFilters(?string $filters): void
    {
        if (null === $filters) {
            return;
        }

        parse_str($filters, $this->filters);
    }

    public function isPublic(): bool
    {
        return $this->public;
    }

    public function setPublic(bool $public): void
    {
        $this->public = $public;
    }

    public function isProtected(): bool
    {
        return $this->protected;
    }

    public function setProtected(bool $protected): void
    {
        $this->protected = $protected;
    }

    /**
     * @return array<SavedFiltersOwnerInterface>
     */
    public function getOwnersWithAccess(): array
    {
        return $this->ownersWithAccess->toArray();
    }

    public function grantOwner(SavedFiltersOwnerInterface $owner): void
    {
        if (!$this->ownersWithAccess->contains($owner)) {
            $this->ownersWithAccess->add($owner);
        }
    }

    public function revokeOwner(SavedFiltersOwnerInterface $owner): void
    {
        if ($this->ownersWithAccess->contains($owner)) {
            $this->ownersWithAccess->removeElement($owner);
        }
    }
}

src/Entity/SavedFiltersOwnerInterface.php
<?php

declare(strict_types=1);

namespace Presta\SonataSavedFiltersBundle\Entity;

interface SavedFiltersOwnerInterface
{
}

src/Controller/SavedFiltersController.php
<?php

declare(strict_types=1);

namespace Presta\SonataSavedFiltersBundle\Controller;

use Doctrine\ORM\EntityManagerInterface;
use Presta\SonataSavedFiltersBundle\Entity\SavedFilters;
use Presta\SonataSavedFiltersBundle\Entity\SavedFiltersOwnerInterface;
use Presta\SonataSavedFiltersBundle\SavedFiltersOwnerAccessor\CannotAccessSavedFiltersOwnerException;
use Presta\SonataSavedFiltersBundle\SavedFiltersOwnerAccessor\SavedFiltersOwnerAccessorInterface;
use Sonata\AdminBundle\Controller\CRUDController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * @extends CRUDController<SavedFilters>
 */
final class SavedFiltersController extends CRUDController
{
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
        private readonly SavedFiltersOwnerAccessorInterface $filterSetHolderAccessor,
    ) {
    }

    public function newAction(Request $request, ValidatorInterface $validator): JsonResponse
    {
        $filtersSet = new SavedFilters();
        $filtersSet->setName($request->request->get('name'));
        $filtersSet->setAdminClass($request->request->get('adminClass'));
        $filtersSet->setFilters($request->request->get('filters'));
        $filtersSet->grantOwner($this->owner());

        $violations = $validator->validate($filtersSet);
        if (count($violations) > 0) {
            return $this->json($violations, Response::HTTP_BAD_REQUEST);
        }

        $this->entityManager->persist($filtersSet);
        $this->entityManager->flush();

        return $this->json(
            [
                'name' => $filtersSet->getName(),
                'filters' => $filtersSet->getFiltersQueryString(),
            ],
            Response::HTTP_CREATED,
        );
    }

    public function protectAction(int $id): RedirectResponse
    {
        $this->owner(); // will guarantee an exception is thrown if no user is available

        if (!$this->admin->isGranted('PROTECT')) {
            throw $this->createAccessDeniedException();
        }

        $object = $this->filter($id);
        $object->setProtected(true);

        $this->entityManager->flush();

        $this->addFlash('success', $this->trans('saved_filters.flash.protected'));

        return $this->redirectToList();
    }

    public function unprotectAction(int $id): RedirectResponse
    {
        $this->owner(); // will guarantee an exception is thrown if no user is available

        if (!$this->admin->isGranted('PROTECT')) {
            throw $this->createAccessDeniedException();
        }

        $object = $this->filter($id);
        $object->setProtected(false);

        $this->entityManager->flush();

        $this->addFlash('success', $this->trans('saved_filters.flash.unprotected'));

        return $this->redirectToList();
    }

    public function shareAction(int $id): RedirectResponse
    {
        $this->owner(); // will guarantee an exception is thrown if no user is available

        $object = $this->filter($id);
        $object->setPublic(true);

        $this->entityManager->flush();

        $this->addFlash('success', $this->trans('saved_filters.flash.shared'));

        return $this->redirectToList();
    }

    public function subscribeAction(int $id): RedirectResponse
    {
        $object = $this->filter($id);
        $object->grantOwner($this->owner());

        $this->entityManager->flush();

        $this->addFlash('success', $this->trans('saved_filters.flash.subscribed'));

        return $this->redirectToList();
    }

    public function unsubscribeAction(int $id): RedirectResponse
    {
        $object = $this->filter($id);
        $object->revokeOwner($this->owner());

        $this->entityManager->flush();

        $this->addFlash('success', $this->trans('saved_filters.flash.unsubscribed'));

        return $this->redirectToList();
    }

    private function filter(int $id): SavedFilters
    {
        $object = $this->admin->getObject($id);
        if ($object === null) {
            throw $this->createNotFoundException(sprintf(
                'Unable to find %s object with id: %s.',
                $this->admin->getClassnameLabel(),
                $id
            ));
        }

        return $object;
    }

    private function owner(): SavedFiltersOwnerInterface
    {
        try {
            return $this->filterSetHolderAccessor->get();
        } catch (CannotAccessSavedFiltersOwnerException $exception) {
            throw $this->createAccessDeniedException(previous: $exception);
        }
    }
}

templates/saved_filters/list_action_protect.html.twig
{% trans_default_domain 'PrestaSonataSavedFiltersBundle' %}

{% if not object.protected and admin.hasRoute('protect') and admin.isGranted('PROTECT') %}
    {% include '@PrestaSonataSavedFilters/saved_filters/list_form_action.html.twig' with {
        url: admin.generateObjectUrl('protect', object),
        title: 'saved_filters.action.protect'|trans,
        icon: 'fa fa-lock',
    } only %}
{% endif %}

templates/saved_filters/list_action_share.html.twig
{% trans_default_domain 'PrestaSonataSavedFiltersBundle' %}

{% if not object.public and admin.hasRoute('share') %}
    {% include '@PrestaSonataSavedFilters/saved_filters/list_form_action.html.twig' with {
        url: admin.generateObjectUrl('share', object),
        title: 'saved_filters.action.share'|trans,
        icon: 'fa fa-share',
    } only %}
{% endif %}

templates/saved_filters/list_action_subscribe.html.twig
{% trans_default_domain 'PrestaSonataSavedFiltersBundle' %}

{% if app.user not in object.ownersWithAccess and admin.hasRoute('subscribe') %}
    {% include '@PrestaSonataSavedFilters/saved_filters/list_form_action.html.twig' with {
        url: admin.generateObjectUrl('subscribe', object),
        title: 'saved_filters.action.subscribe'|trans,
        icon: 'far fa-star',
    } only %}
{% endif %}

templates/saved_filters/list_action_unprotect.html.twig
{% trans_default_domain 'PrestaSonataSavedFiltersBundle' %}

{% if object.protected and admin.hasRoute('unprotect') and admin.isGranted('PROTECT') %}
    {% include '@PrestaSonataSavedFilters/saved_filters/list_form_action.html.twig' with {
        url: admin.generateObjectUrl('unprotect', object),
        title: 'saved_filters.action.unprotect'|trans,
        icon: 'fa fa-lock-open',
    } only %}
{% endif %}

templates/saved_filters/list_action_unsubscribe.html.twig
{% trans_default_domain 'PrestaSonataSavedFiltersBundle' %}

{% if app.user in object.ownersWithAccess and admin.hasRoute('unsubscribe') %}
    {% include '@PrestaSonataSavedFilters/saved_filters/list_form_action.html.twig' with {
        url: admin.generateObjectUrl('unsubscribe', object),
        title: 'saved_filters.action.unsubscribe'|trans,
        icon: 'fas fa-star',
    } only %}
{% endif %}

templates/saved_filters/list_form_action.html.twig
<form action="{{ url }}" method="post">
    <button class="btn btn-xs btn-default" title="{{ title }}">
        <i class="{{ icon }}"></i>
    </button>
</form>

templates/saved_filters_action.html.twig
{% trans_default_domain 'PrestaSonataSavedFiltersBundle' %}

{% if admin is defined and action is defined and action in ['list', 'tree'] and _list_filters_actions is defined and _list_filters_actions is not empty %}
    {% set saved_filters = get_saved_filters(admin) %}
    <ul class="nav navbar-nav navbar-right filters-sets">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-star" aria-hidden="true"></i>
                {{ 'saved_filters.name'|trans }}
                <span class="badge">{{ saved_filters|length }}</span>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu dropdown-menu-scrollable filters-sets-list" role="menu">
                {% for saved_filters in saved_filters %}
                    <li>
                        <a href="{{ saved_filters.filtersQueryString }}">{{ saved_filters.name }}</a>
                    </li>
                {% endfor %}
                <li>
                    <a href="#" class="create-filters-set">
                        <i class="fa fa-plus-circle" aria-hidden="true"></i>
                        {{ 'saved_filters.action.create'|trans }}
                    </a>
                    <form action="{{ path('presta_sonatasavedfilters_savedfilters_new') }}" class="hidden">
                        <div class="form-group col-sm-12">
                            <label class="sr-only" for="saved_filters_name">{{ 'saved_filters.field.name'|trans }}</label>
                            <input type="text" id="saved_filters_name" name="saved_filters[name]" placeholder="{{ 'saved_filters.field.name'|trans }}" class="form-control input-sm" />
                        </div>
                        <input type="hidden" id="saved_filters_admin_class" name="saved_filters[adminClass]" value="{{ admin.class }}" />
                        <div class="form-group col-sm-12">
                            <button type="submit" class="btn btn-sm btn-success pull-right">{{ 'saved_filters.button.submit'|trans }}</button>
                        </div>
                    </form>
                </li>
            </ul>
        </li>
    </ul>
{% endif %}